### PR TITLE
Begining of playlist support

### PR DESCRIPTION
**Pull request by willm**
This adds support for:
 - GET ~/playlists
 - POST ~/playlists
 - GET ~/playlists/{playlistId}
 - POST ~/playlists/{playlistId}

Things to look out for:

This forces the `Accept` header to the value `application/xml` for all requests which has the potential of adding a serialization overhead for endpoints which default to JSON. The reason for this is that the JSON responses returned from the playlist api do not conform to the standard 7digital api schema (ie it doesn't wrap the body in a response node.

The priority order of url and query parameters has changed so that now if an endpoint has url parameters, they will be used and removed first, the remaining parameters will be used as query params.

### CODE REVIEW

**Comment by willm** [comment]
Think the whitespace issues are fixed. @raoulmillais would be good to have feedback on your thoughts about forcing the Accept header as mentioned above.

**Comment by raoulmillais** [comment]
Thanks @willm this is great. The diffs look much clearer. Your approach seems sensible: forcing the accept header makes the current defaults explicit. Let me review properly tomorrow.

**Comment by raoulmillais** [comment]
This looks good.  Can you turn the integration test into an example please?  I'd like to merge this independently of delete work since they feel like distinct pieces of functionality.

**Comment by willm** [comment]
Given a user has an existing persistent basket
When the user signs in
Then a "has persistent basket" variable should be sent

Given a user has no existing persistent basket
When the user signs in
Then no *"has persistent basket"* variable should be sent

Wrap google analytics setting custom var in 
**client/javascript/src/analytics/track.js**

```javascript
 _gaq.push(['_setCustomVar',
      1,                   // This custom var is set to slot #1.  Required parameter.
      'Items Removed',     // The name acts as a kind of category for the user activity.  Required parameter.
      'Yes',               // This value of the custom variable.  Required parameter.
      2                    // Sets the scope to session-level.  Optional parameter.
   ]);
 _gaq.push(['_trackEvent',
      'Shopping', // category of activity
      'Item Removal', // Action
   ]);
```

**Comment by willm** [comment]
All done and I've supressed some of the output as it might have been a bit noisy if used as an example.

**Comment by raoulmillais** [comment]
:+1:

**Pull request merged**
